import { create } from "zustand"
import type { Student } from "@/lib/types"

interface StudentState {
  students: Student[]
  setStudents: (students: Student[]) => void
  addStudent: (student: Student) => void
  updateStudent: (id: string, updates: Partial<Student>) => void
}

// Mock student data
const mockStudents: Student[] = [
  {
    id: "STU001",
    name: "Rahul Sharma",
    program: "Computer Science",
    cohort: "CS-A",
    mentorId: "mentor-1",
    attendancePercent: 45,
    avgScore: 52,
    feeStatus: "overdue",
    attemptsCount: 2,
    backlogsCount: 1,
    lastActiveAt: "2024-03-10",
    compositeRiskScore: 85,
    riskLevel: "red",
    reasons: ["Attendance dropped 25 points in 2 weeks to 45%", "Fees overdue 45 days", "Failed last 2 assessments"],
    avatar: "/student-male-indian.jpg",
  },
  {
    id: "STU002",
    name: "Priya Patel",
    program: "Electronics",
    cohort: "ECE-B",
    attendancePercent: 58,
    avgScore: 48,
    feeStatus: "overdue",
    attemptsCount: 1,
    backlogsCount: 2,
    lastActiveAt: "2024-03-12",
    compositeRiskScore: 82,
    riskLevel: "red",
    reasons: ["Marks declined 18 points from personal baseline", "Fee payment delayed 38 days", "Multiple backlogs"],
    avatar: "/student-female-indian.jpg",
  },
  {
    id: "STU003",
    name: "Arjun Kumar",
    program: "Mechanical",
    cohort: "MECH-B",
    attendancePercent: 62,
    avgScore: 55,
    feeStatus: "partial",
    attemptsCount: 1,
    backlogsCount: 1,
    lastActiveAt: "2024-03-11",
    compositeRiskScore: 78,
    riskLevel: "red",
    reasons: ["Workshop attendance below 65%", "Practical exam scores declining", "Partial fee payment pending"],
    avatar: "/student-male-indian.jpg",
  },
  {
    id: "STU004",
    name: "Sneha Reddy",
    program: "Computer Science",
    cohort: "CS-A",
    attendancePercent: 68,
    avgScore: 58,
    feeStatus: "overdue",
    attemptsCount: 0,
    backlogsCount: 1,
    lastActiveAt: "2024-03-13",
    compositeRiskScore: 75,
    riskLevel: "red",
    reasons: ["Attendance trend declining for 3 weeks", "Recent test scores below 60%", "Fee overdue 28 days"],
    avatar: "/student-female-indian.jpg",
  },
  {
    id: "STU005",
    name: "Vikram Singh",
    program: "Electronics",
    cohort: "ECE-B",
    attendancePercent: 55,
    avgScore: 62,
    feeStatus: "overdue",
    attemptsCount: 1,
    backlogsCount: 0,
    lastActiveAt: "2024-03-09",
    compositeRiskScore: 72,
    riskLevel: "red",
    reasons: ["Critical attendance shortage", "Lab participation very low", "Fee payment overdue 52 days"],
    avatar: "/student-male-indian.jpg",
  },
  {
    id: "STU006",
    name: "Ananya Gupta",
    program: "Computer Science",
    cohort: "CS-B",
    attendancePercent: 72,
    avgScore: 48,
    feeStatus: "paid",
    attemptsCount: 2,
    backlogsCount: 1,
    lastActiveAt: "2024-03-14",
    compositeRiskScore: 68,
    riskLevel: "red",
    reasons: [
      "Major assessment failures in core subjects",
      "Multiple attempts in programming courses",
      "Academic performance declining",
    ],
    avatar: "/student-female-indian.jpg",
  },
  {
    id: "STU007",
    name: "Karthik Nair",
    program: "Mechanical",
    cohort: "MECH-A",
    attendancePercent: 78,
    avgScore: 52,
    feeStatus: "partial",
    attemptsCount: 1,
    backlogsCount: 2,
    lastActiveAt: "2024-03-12",
    compositeRiskScore: 65,
    riskLevel: "red",
    reasons: ["Engineering drawing scores very low", "Multiple backlogs accumulating", "Partial fee payment pending"],
    avatar: "/student-male-indian.jpg",
  },
  {
    id: "STU008",
    name: "Divya Krishnan",
    program: "Electronics",
    cohort: "ECE-A",
    attendancePercent: 65,
    avgScore: 58,
    feeStatus: "overdue",
    attemptsCount: 0,
    backlogsCount: 1,
    lastActiveAt: "2024-03-13",
    compositeRiskScore: 62,
    riskLevel: "red",
    reasons: ["Circuit analysis performance poor", "Lab attendance inconsistent", "Fee payment delayed 35 days"],
    avatar: "/student-female-indian.jpg",
  },
  // Add some amber and green students for completeness
  {
    id: "STU009",
    name: "Rohit Agarwal",
    program: "Computer Science",
    cohort: "CS-A",
    attendancePercent: 78,
    avgScore: 68,
    feeStatus: "paid",
    attemptsCount: 0,
    backlogsCount: 0,
    lastActiveAt: "2024-03-14",
    compositeRiskScore: 45,
    riskLevel: "amber",
    reasons: ["Attendance slightly below target", "Recent quiz scores declining"],
    avatar: "/student-male-indian.jpg",
  },
  {
    id: "STU010",
    name: "Meera Joshi",
    program: "Electronics",
    cohort: "ECE-A",
    attendancePercent: 88,
    avgScore: 82,
    feeStatus: "paid",
    attemptsCount: 0,
    backlogsCount: 0,
    lastActiveAt: "2024-03-15",
    compositeRiskScore: 15,
    riskLevel: "green",
    reasons: [],
    avatar: "/student-female-indian.jpg",
  },
]

export const useStudentStore = create<StudentState>((set) => ({
  students: mockStudents,
  setStudents: (students) => set({ students }),
  addStudent: (student) => set((state) => ({ students: [...state.students, student] })),
  updateStudent: (id, updates) =>
    set((state) => ({
      students: state.students.map((student) => (student.id === id ? { ...student, ...updates } : student)),
    })),
}))
